 .dockerignore                                      |   47 [32m+[m
 .env.example                                       |   52 [32m+[m
 .github/dependabot.yml                             |   65 [32m+[m
 .github/workflows/ci.yml                           |  221 [32m+++[m
 .github/workflows/security.yml                     |  189 [32m+++[m
 .gitignore                                         |   62 [32m+[m
 CONTRIBUTING.md                                    |  129 [32m++[m
 Dockerfile                                         |   52 [32m+[m
 LICENSE                                            |  201 [32m+++[m
 Makefile                                           |   74 [32m+[m
 README.md                                          |  293 [32m++++[m
 SECURITY.md                                        |  222 [32m+++[m
 cmd/dnsdaddy/main.go                               |  329 [32m+++++[m
 deploy/Caddyfile.example                           |   67 [32m+[m
 deploy/diagnose.sh                                 |  226 [32m+++[m
 deploy/dnsdaddy-compose.service                    |   69 [32m+[m
 deploy/dnsdaddy.service                            |   66 [32m+[m
 deploy/healthcheck.sh                              |  162 [32m+++[m
 deploy/install.sh                                  |  184 [32m+++[m
 deploy/production-deploy.sh                        |  354 [32m+++++[m
 dnsdaddy.example.yaml                              |  168 [32m+++[m
 docker-compose.yml                                 |  158 [32m+++[m
 docs/architecture.md                               |  221 [32m+++[m
 docs/deploy.md                                     |  499 [32m+++++++[m
 docs/integrations.md                               |  288 [32m++++[m
 docs/privacy.md                                    |  188 [32m+++[m
 docs/security/semgrep-triage-2026-07-29.md         |   91 [32m++[m
 docs/threat-intel.md                               |  210 [32m+++[m
 go.mod                                             |   23 [32m+[m
 go.sum                                             |   36 [32m+[m
 internal/api/api_test.go                           |  647 [32m+++++++++[m
 internal/api/auth.go                               |  391 [32m++++++[m
 internal/api/handlers_config.go                    |  501 [32m+++++++[m
 internal/api/handlers_dashboard.go                 |  379 [32m++++++[m
 internal/api/handlers_reports.go                   |  370 [32m+++++[m
 internal/api/helpers.go                            |   18 [32m+[m
 internal/api/metrics.go                            |  115 [32m++[m
 internal/api/openapi.go                            |   10 [32m+[m
 internal/api/openapi.yaml                          |  995 [32m++++++++++++++[m
 internal/api/response_safety_test.go               |  242 [32m++++[m
 internal/api/security_test.go                      |  279 [32m++++[m
 internal/api/server.go                             |  258 [32m++++[m
 internal/blocklist/index.go                        |  172 [32m+++[m
 internal/blocklist/index_test.go                   |  155 [32m+++[m
 internal/blocklist/manager.go                      |  370 [32m+++++[m
 internal/blocklist/manager_test.go                 |  443 [32m++++++[m
 internal/blocklist/parse.go                        |  187 [32m+++[m
 internal/blocklist/parse_test.go                   |  110 [32m++[m
 internal/catalog/catalog.go                        |  213 [32m+++[m
 internal/config/config.go                          |  501 [32m+++++++[m
 internal/config/config_test.go                     |  439 [32m++++++[m
 internal/config/yaml.go                            |   38 [32m+[m
 internal/dnsserver/doh.go                          |  200 [32m+++[m
 internal/dnsserver/doh_test.go                     |  135 [32m++[m
 internal/dnsserver/handler.go                      |  399 [32m++++++[m
 internal/dnsserver/handler_test.go                 |  481 [32m+++++++[m
 internal/dnsserver/hardening_test.go               |  184 [32m+++[m
 internal/dnsserver/server.go                       |  132 [32m++[m
 internal/domainutil/domainutil.go                  |  104 [32m++[m
 internal/domainutil/domainutil_test.go             |  107 [32m++[m
 internal/domainutil/fuzz_test.go                   |  110 [32m++[m
 .../testdata/fuzz/FuzzSuffixes/355e4c6e2dcdd06d    |    2 [32m+[m
 internal/httpx/clientaddr.go                       |  155 [32m+++[m
 internal/httpx/clientaddr_test.go                  |  198 [32m+++[m
 internal/policy/engine.go                          |  318 [32m+++++[m
 internal/policy/engine_test.go                     |  283 [32m++++[m
 internal/querylog/querylog.go                      |  158 [32m+++[m
 internal/querylog/querylog_test.go                 |  191 [32m+++[m
 internal/resolver/cache.go                         |  293 [32m++++[m
 internal/resolver/cache_test.go                    |  227 [32m++++[m
 internal/resolver/counter.go                       |   10 [32m+[m
 internal/resolver/inflight_test.go                 |  202 [32m+++[m
 internal/resolver/resolver.go                      |  308 [32m+++++[m
 internal/resolver/upstream.go                      |  322 [32m+++++[m
 internal/resolver/upstream_test.go                 |   73 [32m+[m
 internal/store/domain.go                           |    7 [32m+[m
 internal/store/feeds.go                            |  275 [32m++++[m
 internal/store/ids.go                              |   30 [32m+[m
 internal/store/localfeed.go                        |   83 [32m++[m
 internal/store/logs.go                             |  445 [32m++++++[m
 internal/store/models.go                           |  117 [32m++[m
 internal/store/networks.go                         |  319 [32m+++++[m
 internal/store/policies.go                         |  354 [32m+++++[m
 internal/store/schema.sql                          |  126 [32m++[m
 internal/store/seed.go                             |  141 [32m++[m
 internal/store/store.go                            |  111 [32m++[m
 internal/store/store_test.go                       |  509 [32m+++++++[m
 internal/store/tokens.go                           |  146 [32m++[m
 internal/version/version.go                        |   43 [32m+[m
 internal/web/embed.go                              |   62 [32m+[m
 internal/web/static/app.css                        |  541 [32m++++++++[m
 internal/web/static/app.js                         | 1436 [32m++++++++++++++++++++[m
 internal/web/static/favicon.svg                    |   10 [32m+[m
 internal/web/static/index.html                     |   86 [32m++[m
 internal/web/static/logo.svg                       |   28 [32m+[m
 95 files changed, 21240 insertions(+)
