package detect

import (
	"fmt"
	"time"
)

// DGADetector looks for clients resolving algorithmically generated domains.
//
// Malware that uses a domain generation algorithm computes a list of candidate
// rendezvous domains from a seed — often the date — and tries them until one
// answers. The operator registers only one or two, so from the resolver's seat
// the observable is a host asking for many unrelated registered domains with
// random-looking second-level labels, nearly all of which do not exist.
//
// This is a *heuristic*, and the word is used precisely. It measures surface
// statistics of the label: vowel distribution, consonant runs, digit fraction,
// and per-character entropy. It does not use a model, it is not trained on
// anything, and it will not recognise a DGA that generates pronounceable
// domains from a word list — those exist, they defeat this approach
// completely, and saying so is more useful than implying coverage that is not
// there. Detecting them is a research problem, tracked on the roadmap rather
// than claimed here.
type DGADetector struct {
	cfg   DGAConfig
	track *tracker[*dgaState]
}

// DGAConfig holds the tunable thresholds.
type DGAConfig struct {
	Window     time.Duration
	MaxTracked int

	// RandomnessThreshold is the randomnessIndex above which a second-level
	// label counts as a candidate.
	RandomnessThreshold float64
	// MinCandidates gates the detector.
	MinCandidates int

	FullConfidenceCandidates int
	DomainCap                int
}

// DefaultDGAConfig returns the shipped thresholds.
func DefaultDGAConfig() DGAConfig {
	return DGAConfig{
		Window:                   10 * time.Minute,
		MaxTracked:               4096,
		RandomnessThreshold:      0.45,
		MinCandidates:            8,
		FullConfidenceCandidates: 60,
		DomainCap:                1024,
	}
}

type dgaState struct {
	// seenParents deduplicates work: a parent is scored once per window
	// however many times it is queried.
	seenParents *boundedSet
	candidates  *boundedSet
	tlds        *boundedSet

	randomnessSum float64
	candidateNX   int
	candidateHits int

	clientName string
	networkID  string
	examples   []string
}

// NewDGADetector builds a DGA-like domain detector.
func NewDGADetector(cfg DGAConfig) *DGADetector {
	if cfg.Window <= 0 {
		cfg = DefaultDGAConfig()
	}
	capacity := cfg.DomainCap
	return &DGADetector{
		cfg: cfg,
		track: newTracker(cfg.MaxTracked, cfg.Window, func() *dgaState {
			return &dgaState{
				seenParents: newBoundedSet(capacity),
				candidates:  newBoundedSet(capacity),
				tlds:        newBoundedSet(64),
			}
		}),
	}
}

// Name implements Detector.
func (d *DGADetector) Name() string { return "dga_like" }

// Info implements Detector.
func (d *DGADetector) Info() DetectorInfo {
	return DetectorInfo{
		Name:      d.Name(),
		EventType: EventDGALike,
		Title:     "Algorithmically generated domains",
		Description: "Scores the second-level label of each distinct registered domain a client " +
			"resolves on four surface statistics — vowel distribution, consonant runs, digit " +
			"fraction and entropy — and reports clients querying many high-scoring domains, " +
			"especially where those domains do not resolve. Word-list DGAs are not detected.",
		Maturity:    MaturityExperimental,
		MaxSeverity: SeverityHigh,
		Window:      d.cfg.Window.String(),
		MITRE:       dgaTechniques(),
		SignalNames: []string{
			"algorithmic_domain_count", "mean_randomness", "candidate_nxdomain_ratio",
			"distinct_tlds",
		},
		FalsePositives: []string{
			"Cloud and CDN hostnames frequently contain generated identifiers; the shipped " +
				"exclusion list covers the common providers but not every SaaS vendor.",
			"URL shorteners, tracking domains, and some advertising infrastructure use short " +
				"random-looking registered domains.",
			"Internationalised domains are punycode and machine-generated by definition; they are " +
				"excluded from scoring.",
			"Security tooling that resolves generated names deliberately, including this " +
				"project's own lab scenarios.",
		},
		Enforces: false,
	}
}

// Observe implements Detector.
func (d *DGADetector) Observe(e *Event) {
	if e.Excluded || !e.HasParent {
		return
	}

	ent := d.track.get(e.ClientKey(), e.Time)
	s := ent.state

	if e.ClientName != "" {
		s.clientName = e.ClientName
	}
	if e.NetworkID != "" {
		s.networkID = e.NetworkID
	}

	// The second-level label is the part a DGA generates; the TLD is chosen
	// from a fixed list and carries no randomness of its own.
	labels := labelsOf(e.Parent)
	if len(labels) < 2 {
		return
	}
	sld := labels[0]
	if isInternationalised(sld) {
		return
	}

	isNew := s.seenParents.add(e.Parent)

	if isNew {
		if r := randomnessIndex(sld); r >= d.cfg.RandomnessThreshold {
			s.candidates.add(e.Parent)
			s.randomnessSum += r
			s.tlds.add(labels[len(labels)-1])
			if len(s.examples) < 5 {
				s.examples = append(s.examples, e.Parent)
			}
		}
	}

	// Resolution outcome is tracked for candidate domains only: the DGA
	// signature is that most generated names do not exist, and mixing in the
	// client's ordinary browsing would wash that out.
	if s.candidates.contains(e.Parent) {
		s.candidateHits++
		if e.NXDomain {
			s.candidateNX++
		}
	}
}

// Evaluate implements Detector.
func (d *DGADetector) Evaluate(now time.Time) []Finding {
	var out []Finding
	for _, ent := range d.track.due(now) {
		if f, ok := d.score(ent, now); ok {
			out = append(out, f)
		}
		d.track.reset(ent, now)
	}
	return out
}

// Sweep implements Detector.
func (d *DGADetector) Sweep(now time.Time) { d.track.sweep(now) }

// Tracked implements Detector.
func (d *DGADetector) Tracked() int { return d.track.len() }

func (d *DGADetector) score(ent *entry[*dgaState], now time.Time) (Finding, bool) {
	s := ent.state
	candidates := s.candidates.count()
	if candidates < d.cfg.MinCandidates {
		return Finding{}, false
	}

	meanRandomness := s.randomnessSum / float64(candidates)
	nxRatio := 0.0
	if s.candidateHits > 0 {
		nxRatio = float64(s.candidateNX) / float64(s.candidateHits)
	}

	signals := []Signal{
		signal("algorithmic_domain_count",
			"Distinct registered domains whose second-level label scored above the randomness "+
				"threshold.",
			float64(candidates), 8, 60, 0.40),
		signal("mean_randomness",
			"Mean randomness index of those labels, on 0..1, combining vowel distribution, "+
				"consonant runs, digit fraction and entropy in equal parts.",
			meanRandomness, 0.45, 0.80, 0.25),
		signal("candidate_nxdomain_ratio",
			"Share of lookups for those domains that did not resolve. A generation algorithm "+
				"produces far more names than the operator registers, so most must fail.",
			nxRatio, 0.30, 0.90, 0.25),
		signal("distinct_tlds",
			"Number of different top-level domains among the candidates. Generation algorithms "+
				"commonly rotate across a fixed TLD set.",
			float64(s.tlds.count()), 2, 8, 0.10),
	}

	var score float64
	for _, sig := range signals {
		score += sig.Contribution
	}

	severity := severityFor(score, SeverityHigh)
	if severity.Rank() < SeverityLow.Rank() {
		return Finding{}, false
	}

	clientIP := clientIPOf(ent.key)

	return Finding{
		Time:       now,
		EventType:  EventDGALike,
		Severity:   severity,
		Score:      round2(score),
		Confidence: confidenceFor(score, candidates, d.cfg.MinCandidates, d.cfg.FullConfidenceCandidates),
		Client: Client{
			IP:        clientIP,
			Name:      s.clientName,
			NetworkID: s.networkID,
		},
		Title: "Algorithmically generated domains",
		Summary: fmt.Sprintf(
			"%s resolved %d distinct registered domains with random-looking second-level labels "+
				"in %s (mean randomness %.2f, %.0f%% did not resolve, %d top-level domains). "+
				"Examples: %v.",
			describeClient(clientIP, s.clientName, s.networkID),
			candidates, d.cfg.Window, meanRandomness, nxRatio*100, s.tlds.count(), s.examples),
		Signals: signals,
		Evidence: map[string]any{
			"algorithmic_domains":      candidates,
			"domains_examined":         s.seenParents.count(),
			"mean_randomness":          round2(meanRandomness),
			"candidate_lookups":        s.candidateHits,
			"candidate_nxdomain":       s.candidateNX,
			"candidate_nxdomain_ratio": round2(nxRatio),
			"distinct_tlds":            s.tlds.count(),
			"examples":                 s.examples,
		},
		Window: Window{Start: ent.start, End: now},
		MITRE:  dgaTechniques(),
		FalsePositives: []string{
			"Cloud, CDN and SaaS hostnames containing generated identifiers.",
			"URL shorteners and advertising infrastructure using short random registered domains.",
			"Deliberate enumeration by security tooling.",
		},
		NextSteps: []string{
			"Look at the example domains. A DGA produces names with a consistent length and " +
				"character-set fingerprint; a SaaS vendor's hostnames do not.",
			"Check registration dates for any candidate that did resolve — that one is the " +
				"rendezvous point, and it is usually days old.",
			"Correlate with the nxdomain_burst detector for the same client and window.",
			"Treat a confirmed match as an infected endpoint: the resolver sees the symptom, the " +
				"host has the cause.",
		},
		Detector: d.Name(),
		Maturity: MaturityExperimental,
	}, true
}
